travis:
  secure:
    BINSTAR_TOKEN: DHNeOA1fr0Zry12ZKFDtTfcxUb6qwbBbFpdYiNN9I0Mms2sdIs8fftu1r5iSIZWNCh3zgwKL3khx0SBIdkMzf/VAeHH/rAPc/ItrXfoOfnLPeUESAAg6YV2UnNbocgkBBvqTPjkLegtNFS7R9tT8WKopH9Hl53YsMuugzA95qzEiSMgfd3F7h5DnbawYt9cbCV51VDkTCfMFCexij0CiDNsDtVFoz5oqhkUCoP1ZJfgRpV8GVVK0XMA6aew+hVQK3b4d5v1ZgAppY/I+TEns1nZF/Zw91Em/kMF8gK7cwsjK6dEfpAIC+FfpoDYAvECkDTkWfUkO+EpUuDR9G6PrRYFLGZxt/CNBtit0cvGhNo8mBT/xAjZUAS/i9YDetnT94ET2a4rNpQrq5eD8RJ0N+rJLfmZe04hPh9OnGYz0rA1AnPBqy5esu9NYhfa99BmW2pgQHKJoZxgcXYBZMk6cATXosc6V0G6EOp9S8kKITmnrflfNnc7tQxT/vhmKbaTZuDUX5LYwaGwWLx9r00742Qh6Z5PSjm+Mz7J8vuBy3kA7H1oSFMLzfsFpIFuEEbD810th4vFmTmiwKoxFeZhfXqCalYpM5xx6vz+KS1hfWbR8wimB144GFGemPW+XcvrZ2dFugcbvwoPj6usuULSrcv1+IGUL0hqBJViO41+3HsE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
